[package]
name = "camino"
description = "UTF-8 paths"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = [
    "Without Boats <saoirse@without.boats>",
    "Ashley Williams <ashley666ashley@gmail.com>",
    "Steve Klabnik <steve@steveklabnik.com>",
]
edition = "2018"
